### ISSUE TITLE
NullPointerException: LOGABCK-1717 regression 

### ISSUE THREAD

**Issue by Nowheresly** [qos-ch/logback#715]
Hi,
Starting with logback-classic version 1.4.9, I have the following error:

```
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because "classLoader" is null
	at ch.qos.logback.classic.util.ContextInitializer.instantiateConfiguratorByClassName(ContextInitializer.java:104)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:94)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:65)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:52)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:195)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:182)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:490)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:476)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:425)
```

This error happens because the jdk specifies that getClassLoader() may return null when the class is loaded from the bootstrap classloader. See [here](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getClassLoader--).

Unfortunately, since the commit LOGABCK-1717, autoConfig() will throw a NullPointerException when getClassLoader() returns null. The same code is working fine with version 1.4.8 and below.

**Comment by Nowheresly** [comment]
Just made a PR to handle this case.

**Comment by ceki** [comment]
@Nowheresly  Thank you for this report. 

Can you describe your environment? What type of application is this? Which JDK? OS?  More importantly, where is logback-core.jar located?

**Comment by Nowheresly** [comment]
Thanks for your reply.
We are using logback with a java agent (see [here](https://docs.oracle.com/javase%2F9%2Fdocs%2Fapi%2F%2F/java/lang/instrument/package-summary.html))

For this project: https://github.com/glowroot/glowroot

OS: linux
jdk 8 / 11 / 17 / 20

I will try your commit.

**Comment by Nowheresly** [comment]
Hi @ceki 
I confirm that logback 1.4.14 fixes the issue.
Thank you !!
