### ISSUE TITLE
logback 1.2.6 AsyncAppender-Worker-ASYNC_STDOUT worker thread hang at native write method.

### ISSUE THREAD

**Issue by peaceyear** [qos-ch/logback#730]
The AsyncAppender-Worker-ASYNC_STDOUT worker stack is as follows:

at java.io.FileOutputStream.writeBytes(Native Method)
at java.io.FileOutputStream.write(FileOutputStream.java:326)
at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
- locked [0x00000000b013a610] (a java.io.BufferedOutputStream)
at java.io.PrintStream.write(PrintStream.java:480)
- locked [0x00000000b011d570] (a java.io.PrintStream)
at java.io.FilterOutputStream.write(FilterOutputStream.java:97)at ch.qos.logback.core.joran.spi.ConsoleTarget$1.write(ConsoleTarget.java:37)
at ch.qos.logback.core.OutputStreamAppender.writeBytes(OutputStreamAppender.java:199)
at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:231)
at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
at ch.qos.logback.core.AsyncAppenderBase$Worker.run(AsyncAppenderBase.java:290)
--

then the arrayBlockingQueue soon be full, and all business threads stand awaiting.
It happened once, and is difficult to repeat in the production environment.
Could you tell me how can I find the cause of what happened in the invocation of write?
The Java application runs in the containerd runtime on linux os orchestrated by Kubernetes. thanks!

**Comment by peaceyear** [comment]
sorry, The Java application runs in the docker runtime on linux os orchestrated by Kubernetes.
