### ISSUE TITLE
All threads blocked

### ISSUE THREAD

**Issue by koszta5** [qos-ch/logback#786]
Logback version :1.2.11
Springboot version: 2.7.4

Apparently in some cases all locks are lost and logback is just "stuck" - only restart helps. Thread  dump is attached
[StuckLogback.threads.txt](https://github.com/qos-ch/logback/files/14479030/StuckLogback.threads.txt)

All threads remain in this state WAITING for lock endlessly
`"http-nio-8184-exec-1" #139 daemon prio=5 os_prio=0 cpu=53544.34ms elapsed=232090.85s tid=0x00002af5d1b77800 nid=0x15fe7 waiting on condition  [0x00002af676207000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.19/Native Method)
	- parking to wait for  <0x00000000e0c37af0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.19/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.19/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.19/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.19/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.19/ReentrantLock.java:267)
	at ch.qos.logback.core.OutputStreamAppender.writeBytes(OutputStreamAppender.java:197)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:231)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:398)
	at ch.qos.logback.classic.Logger.debug(Logger.java:486)
	at com.ourcomapany.integration.distribution.v2.delivery.TokenService.addToCache(TokenService.java:233)` 

This bug is very closely related to issue originally reported here: https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1406?filter=allopenissues (same thing really). It is also similar to this: https://github.com/qos-ch/logback/issues/767

**Comment by sunl888** [comment]
I also encountered this issue, it will be resolved after restarting
[jstack.txt](https://github.com/qos-ch/logback/files/14849668/jstack.txt)

**Comment by koszta5** [comment]
well that is not resolving this problem :(

**Comment by ceki** [comment]
Under which JDK version is this occurring?

**Comment by koszta5** [comment]
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment Temurin-11.0.19+7 (build 11.0.19+7)
OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (build 11.0.19+7, mixed mode)

**Comment by jinshuai86** [comment]
> @koszta5 Under which JDK version is this occurring?

Can you take a look at the problem in the link?  https://jira.qos.ch/browse/LOGBACK-1406

It's very similar to this issue, I've also encountered this problem.


Thread 402: (state = BLOCKED)
 - sun.misc.Unsafe.park(boolean, long) @bci=0 (Compiled frame; information may be imprecise)
 - java.util.concurrent.locks.LockSupport.park(java.lang.Object) @bci=14, line=175 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt() @bci=1, line=836 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.util.concurrent.locks.AbstractQueuedSynchronizer$Node, int) @bci=67, line=870 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(int) @bci=17, line=1199 (Compiled frame)
 - java.util.concurrent.locks.ReentrantLock$NonfairSync.lock() @bci=21, line=209 (Compiled frame)
 - java.util.concurrent.locks.ReentrantLock.lock() @bci=4, line=285 (Compiled frame)
 - ch.qos.logback.core.OutputStreamAppender.subAppend(java.lang.Object) @bci=28, line=210 (Compiled frame)
 - ch.qos.logback.core.OutputStreamAppender.append(java.lang.Object) @bci=10, line=100 (Compiled frame)
 - ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(java.lang.Object) @bci=123, line=84 (Compiled frame)
 - ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(java.lang.Object) @bci=32, line=51 (Compiled frame)

**Comment by koszta5** [comment]
Sorry, but no - if you examine e.g. my very recent thread dump here:
https://jstack.review/

You will find out that all my threads are simply WAITING for a lock that is now lost (no other thread is holding it)
[stuckLogback.threads.txt](https://github.com/qos-ch/logback/files/15186339/stuckLogback.threads.txt)

Lock 0x0000000701dc5ff0 is completely lost to the JVM :( Causing the whole app to get stuck

**Comment by ceki** [comment]
@koszta5 The 1.2 branch is about 8 years old now. Would it be possible for your to upgrade to logback 1.5?

**Comment by apflieger** [comment]
I had this problem on 1.4.11 and rollbacked our virtual thread migration.
We couldn't reproduce the crash so while I can upgrade to 1.5, I can't test virtual threads again blindly

**Comment by long-forgotten** [comment]
We have a similar issue #776 here using async logging

**Comment by sunl888** [comment]
> I had this problem on 1.4.11 and rollbacked our virtual thread migration. We couldn't reproduce the crash so while I can upgrade to 1.5, I can't test virtual threads again blindly

We are also.

**Comment by long-forgotten** [comment]
@koszta5 Are you using async logging mechanism? We observe that async logging suffers this 'stuck' more.

**Comment by koszta5** [comment]
nope. This is sync logging

**Comment by jhinch** [comment]
I have reproduced the problem in an isolated setup:

https://github.com/jhinch/logback-virtual-threads-deadlock/blob/main/app/src/main/java/VirtualThreadLogbackDeadlock.java

This is the exact same deadlock scenario which was described by Netflix in this blog post:

https://netflixtechblog.com/java-21-virtual-threads-dude-wheres-my-lock-3052540e231d

I believe that this problem may be mitigated by using the [async appender](https://logback.qos.ch/manual/appenders.html#AsyncAppender) with `neverBlock` set to `true`. However this does have the impact of potentially dropping logs.

Another option which may work to fix this would be to actually replace the use of `ReentrantLock` in `OutputStreamAppender` with a `synchronized` block. This will cause all logging to be pinned to the carrier thread for the duration of the log occurring, but will avoid the deadlock.

This is unlikely to be fixed completely until https://openjdk.org/jeps/491 is implemented

**Comment by qsLI** [comment]
> Sorry, but no - if you examine e.g. my very recent thread dump here: https://jstack.review/
> 
> You will find out that all my threads are simply WAITING for a lock that is now lost (no other thread is holding it) [stuckLogback.threads.txt](https://github.com/qos-ch/logback/files/15186339/stuckLogback.threads.txt)
> 
> Lock 0x0000000701dc5ff0 is completely lost to the JVM :( Causing the whole app to get stuck

Same here! And I examine the thread who own the lock with hsdb，but the field is null!
```
hsdb> inspect 0x000000027be85f38
instance of Oop for java/util/concurrent/locks/ReentrantLock$NonfairSync @ 0x000000027be85f38 (size = 32)
_mark: 365743755841
_metadata._compressed_klass: InstanceKlass for java/util/concurrent/locks/ReentrantLock$NonfairSync
exclusiveOwnerThread: null
head: Oop for java/util/concurrent/locks/AbstractQueuedSynchronizer$ExclusiveNode @ 0x00000004e5225568
tail: Oop for java/util/concurrent/locks/AbstractQueuedSynchronizer$ExclusiveNode @ 0x00000004a64afa98
state: 0
```

<img width="881" alt="image" src="https://github.com/user-attachments/assets/0b414899-a9b6-42ab-b0f1-9b27e7571134">

**Comment by ceki** [comment]
Version 1.2 branch is about ten years old. Moreover, versions 1.2.x, 1.3.x and 1.4.x have reached END-OF-LIFE status.

How about migrating to a more recent version of spring-boot?
