### ISSUE TITLE
Randomly occuring NPE when logging 

### ISSUE THREAD

**Issue by nadrian4** [qos-ch/logback#822]
Hi, I'm working with Java 17, SLF4j 2.0.12 and logback 1.5.2 and from time to time I randomly get following error when I try to log something:

```
java.lang.NullPointerException: Cannot invoke "ch.qos.logback.core.Appender.doAppend(Object)" because "appenderArray[i]" is null
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:272)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:259)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:426)
        at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:402)
        at ch.qos.logback.classic.Logger.info(Logger.java:588)
```

The configuration file is as below:
```
<configuration scan="true" scanPeriod="120 seconds">
	<appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
		<file>log/history.log</file>
		<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
			<fileNamePattern>log/history-%d{MM-dd-yyyy}.log</fileNamePattern>
		</rollingPolicy>
		<encoder>
			<pattern>%date{HH:mm:ss.SSS} %-5level %logger{0} - %msg%n</pattern>
		</encoder>
	</appender>
	<appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
		<queueSize>1024</queueSize>
		<neverBlock>true</neverBlock>
		<appender-ref ref="FILE" />
	</appender>
	<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>%date{HH:mm:ss.SSS} %-5level %logger{0} - %msg%n</pattern>
		</encoder>
	</appender>
	<appender name="stash" class="net.logstash.logback.appender.LogstashUdpSocketAppender">
		<filter class="ch.qos.logback.classic.filter.ThresholdFilter">
			<level>ERROR</level>
		</filter>
		<host>logstash</host>
		<port>5056</port>
		<layout class="net.logstash.logback.layout.LogstashLayout">
			<customFields>{"userDir":"${user.dir}","hostname":"${HOSTNAME}"}</customFields>
		</layout>
	</appender>
	<root level="INFO">
		<appender-ref ref="stash" />
		<appender-ref ref="ASYNC" />
	</root>
</configuration>
```

What could be the cause?

**Comment by ceki** [comment]
@nadrian4 Can you tell when does this issue occurs? Is it during reconfiguration?

**Comment by ceki** [comment]
@nadrian4  I have tried to [reproduce this issue](https://github.com/qos-ch/logback/blob/master/logback-core/src/test/java/ch/qos/logback/core/util/COWArrayListConcurrencyTest.java)  but without success. Does the issue occur if you do not use `LogstashUdpSocketAppender`? Do you change the `logback.xml` configuration file often?

**Comment by nadrian4** [comment]
Hi @ceki it occurs in non-deterministic conditions even if the reconfiguration is not done at all (e.g. at night when nobody works with these files). The number of threads is aobut 150-200 platform threads. 

I have a lot of applications (7000) working with logback and this exception occurs once a week or two. It's really tough to find something that these cases have in common. We worked around this issue by handling the exception, but would be great to find solution.

We didn't try without LogstashUdpSocketAppender, hard to say if it would help. Unfortunately the problem occurs really rarely and we can't switch off Logstash appender, as some part of our system relies on it.
