### ISSUE TITLE
java.lang.IndexOutOfBoundsException at TimeBasedFileNamingAndTriggeringPolicyBase.start

### ISSUE THREAD

**Issue by TomHuynh17** [qos-ch/logback#856]
I got crash from Crashlytics report as follows which happen only on OS 13, Samsung phone model:

Caused by java.lang.IndexOutOfBoundsException: index=-987076581 out of bounds (limit=26614624)
       at java.nio.Buffer.checkIndex(Buffer.java:709)
       at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:240)
       at android.icu.impl.ICUBinary.compareKeys(ICUBinary.java:375)
       at android.icu.impl.ICUBinary$DatPackageReader.binarySearch(ICUBinary.java:137)
       at android.icu.impl.ICUBinary$DatPackageReader.getData(ICUBinary.java:99)
       at android.icu.impl.ICUBinary$PackageDataFile.getData(ICUBinary.java:277)
       at android.icu.impl.ICUBinary.getDataFromFile(ICUBinary.java:524)
       at android.icu.impl.ICUBinary.getData(ICUBinary.java:498)
       at android.icu.impl.ICUBinary.getData(ICUBinary.java:453)
       at android.icu.impl.ICUResourceBundleReader$ReaderCache.createInstance(ICUResourceBundleReader.java:191)
       at android.icu.impl.ICUResourceBundleReader$ReaderCache.createInstance(ICUResourceBundleReader.java:180)
       at android.icu.impl.SoftCache.getInstance(SoftCache.java:71)
       at android.icu.impl.ICUResourceBundleReader.getReader(ICUResourceBundleReader.java:235)
       at android.icu.impl.ICUResourceBundle.createBundle(ICUResourceBundle.java:1422)
       at android.icu.impl.ICUResourceBundle$4.load(ICUResourceBundle.java:1295)
       at android.icu.impl.ICUResourceBundle$1.createInstance(ICUResourceBundle.java:97)
       at android.icu.impl.ICUResourceBundle$1.createInstance(ICUResourceBundle.java:94)
       at android.icu.impl.SoftCache.getInstance(SoftCache.java:71)
       at android.icu.impl.ICUResourceBundle.instantiateBundle(ICUResourceBundle.java:1282)
       at android.icu.impl.ICUResourceBundle.getBundleInstance(ICUResourceBundle.java:1255)
       at android.icu.impl.ICUResourceBundle.getBundleInstance(ICUResourceBundle.java:1234)
       at android.icu.util.UResourceBundle.instantiateBundle(UResourceBundle.java:361)
       at android.icu.util.UResourceBundle.getBundleInstance(UResourceBundle.java:147)
       at android.icu.util.UResourceBundle.getBundleInstance(UResourceBundle.java:226)
       at android.icu.impl.TimeZoneNamesImpl.initialize(TimeZoneNamesImpl.java:421)
       at android.icu.impl.TimeZoneNamesImpl.<init>(TimeZoneNamesImpl.java:67)
       at android.icu.impl.TimeZoneNamesFactoryImpl.getTimeZoneNames(TimeZoneNamesFactoryImpl.java:27)
       at android.icu.text.TimeZoneNames$Cache.createInstance(TimeZoneNames.java:496)
       at android.icu.text.TimeZoneNames$Cache.createInstance(TimeZoneNames.java:487)
       at android.icu.impl.SoftCache.getInstance(SoftCache.java:71)
       at android.icu.text.TimeZoneNames.getInstance(TimeZoneNames.java:157)
       at android.icu.text.TimeZoneNames.getInstance(TimeZoneNames.java:169)
       at java.util.TimeZone.getDisplayName(TimeZone.java:410)
       at java.util.Date.toString(Date.java:1067)
       at java.lang.String.valueOf(String.java:4092)
       at java.lang.StringBuilder.append(StringBuilder.java:179)
       at ch.qos.logback.core.rolling.TimeBasedFileNamingAndTriggeringPolicyBase.start(TimeBasedFileNamingAndTriggeringPolicyBase.java:184)
       at ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP.start(SizeAndTimeBasedFNATP.java:1)
       at ch.qos.logback.core.rolling.TimeBasedRollingPolicy.start(TimeBasedRollingPolicy.java:130)

**Comment by ceki** [comment]
Which version of logback is this?

**Comment by TomHuynh17** [comment]
I use a lite version in Android
implementation 'com.github.tony19:logback-android:3.0.0'
