### ISSUE TITLE
Last argument of log message stripped if Throwable, even when cause is given as well

### ISSUE THREAD

**Issue by Maldivia** [qos-ch/logback#876]
If a `Throwable` type is passed to match the last `{}` argument, it is ignored, and the formatted log message will write `{}` instead.

Example:
```java
package com.test;

import ch.qos.logback.core.Appender;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.event.Level;

public class Test {
  static final Logger log = LoggerFactory.getLogger(Test.class);

  public static void main(String[] args) {
    log.info("SLF4J Version: {}", Logger.class.getPackage().getImplementationVersion());
    log.info("Logback Version: {}", Appender.class.getPackage().getImplementationVersion());

    Exception ex = new Exception("Some message");
    log.error("Exception Message: {}", ex, ex);

    log.makeLoggingEventBuilder(Level.WARN)
        .setMessage("Exception Message: {}")
        .addArgument(ex)
        .setCause(ex)
        .log();
  }
}
```

Expected output:
```
[main] INFO com.test.Test -- SLF4J Version: 2.0.15
[main] INFO com.test.Test -- Logback Version: 1.5.11
[main] ERROR com.test.Test -- Exception Message: java.lang.Exception: Some message
java.lang.Exception: Some message
	at com.test.Test.main(Test.java:15)
[main] WARN com.test.Test -- Exception Message: java.lang.Exception: Some message
java.lang.Exception: Some message
	at com.test.Test.main(Test.java:15)
```

Actual output:
```
[main] INFO com.test.Test -- SLF4J Version: 2.0.15
[main] INFO com.test.Test -- Logback Version: 1.5.11
[main] ERROR com.test.Test -- Exception Message: {}
java.lang.Exception: Some message
	at com.test.Test.main(Test.java:15)
[main] WARN com.test.Test -- Exception Message: {}
java.lang.Exception: Some message
	at com.test.Test.main(Test.java:15)
```

**Comment by ceki** [comment]
Linked to https://jira.qos.ch/browse/LOGBACK-1775

**Comment by ceki** [comment]
Fixed in commit 85968fa3fe217a79760ec2b4a275e68cefeb8656

**Comment by Maldivia** [comment]
> Please note that `log.makeLoggingEventBuilder(Level.WARN)` is a longer form for `log.atWarn()`.
Yeah, it was just to show that creating it using the builder, calling `setCause` explicitly also had the issue.
