### ISSUE TITLE
PATTERN_RULE_REGISTRY no longer accepts class names

### ISSUE THREAD

**Issue by snicoll** [qos-ch/logback#885]
I am trying to upgrade from Logback 1.5.12 to 1.5.13 and be0b5e0 is [affecting us](https://ge.spring.io/s/3vohaeh7xvghs/tests/overview?outcome=FAILED).

We do have a number of additional classnames that we set in the `PATTERN_RULE_REGISTRY` for our own support. It looks like we should be providing a supplier now. If I understood this correctly, this is surprising in a patch release.

If this is indeed what we should be doing now, how do we maintain compatibility with Logback < 1.5.13 whist providing support for the latest patch release?

**Comment by ceki** [comment]
@snicoll Sorry to hear this. Can you please point me to the code on your side causing the issue ?

**Comment by ceki** [comment]
There is already a compatibility layer for existing subclasses of PatternLayout. The path going through the context was missed. It will be fixes shortly in 1.5.14.

**Comment by bgiaccio** [comment]
Confirmed the new version works with spring boot 3.3.3
I appreciate the quick resolution.

**Comment by edigu** [comment]
We are still seeing full of PARSER_ERRORs like below, using Spring Boot `3.3.7` + Logback `1.5.14`

application.yaml
```yaml
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:0}){magenta} %clr(---){faint} %clr([%10.10t]){green} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
```

logback-spring.xml:
```
<?xml version="1.0" encoding="UTF-8" ?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>
    <include resource="org/springframework/boot/logging/logback/file-appender.xml"/>
    <springProfile name="staging | production">
        <root level="${SPRING_ROOT_LOG_LEVEL:-INFO}">
            <appender-ref ref="CONSOLE"/>
            <appender-ref ref="FILE"/>
        </root>
    </springProfile>
    <springProfile name="local | default">
        <root level="DEBUG">
            <appender-ref ref="CONSOLE"/>
        </root>
    </springProfile>
</configuration>
```
Stacktrace:
```
%PARSER_ERROR[d] %PARSER_ERROR[p] 81160 --- [%PARSER_ERROR[t]] %PARSER_ERROR[logger] : %PARSER_ERROR[m]%PARSER_ERROR[n]
java.lang.IllegalStateException: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.pattern.parser.Compiler@4564e94b - There is no conversion class registered for conversion word [d]
ERROR in ch.qos.logback.core.pattern.parser.Compiler@4564e94b - [d] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@54534abf - There is no conversion class registered for conversion word [p]
ERROR in ch.qos.logback.core.pattern.parser.Compiler@54534abf - [p] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@51745f40 - There is no conversion class registered for conversion word [t]
ERROR in ch.qos.logback.core.pattern.parser.Compiler@51745f40 - [t] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@45673f68 - There is no conversion class registered for conversion word [logger]
ERROR in ch.qos.logback.core.pattern.parser.Compiler@45673f68 - [logger] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@27abb83e - There is no conversion class registered for conversion word [m]
ERROR in ch.qos.logback.core.pattern.parser.Compiler@27abb83e - [m] is not a valid conversion word
ERROR in ch.qos.logback.core.pattern.parser.Compiler@27abb83e - There is no conversion class registered for conversion word [n]
ERROR in ch.qos.logback.core.pattern.parser.Compiler@27abb83e - [n] is not a valid conversion word
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:347)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:298)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
```

**Comment by ceki** [comment]
@edigu I am looking into it. Can you reproduce the problem in a smaller example to speed things up?

**Comment by edigu** [comment]
Ok my bad, `logback-classic` in pom.xml was

```xml
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.5.14</version>
        </dependency>
```

while `logback-core` was falling back to spring's pinned version `1.5.12`. Explicitly added `logback-core` in `pom.xml` as well and confirm that `1.5.14` works. 🥳 

Thanks a lot.

**Comment by ceki** [comment]
@edigu Since this may be a common situation, version 1.5.15, i.e the next version of logback-classic, will detect and inform the user if logback-core has a different (older) version.

**Comment by ceki** [comment]
Logback-classic version 1.5.15 released earlier will detect any logback-core and logback-classic mismatch and warn the user.
