### ISSUE TITLE
`ClassCastException` from `Compiler` on logback upgrade from 1.5.12 to 1.5.13

### ISSUE THREAD

**Issue by pzygielo** [qos-ch/logback#887]
Not sure who to blame, but with spring on logback upgrade from 1.5.12 to 1.5.13 I'm getting:
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.function.Supplier (java.lang.String and java.util.function.Supplier are in module java.base of loader 'bootstrap')
	at ch.qos.logback.core.pattern.parser.Compiler.createCompositeConverter(Compiler.java:120)
	at ch.qos.logback.core.pattern.parser.Compiler.compile(Compiler.java:48)
	at ch.qos.logback.core.pattern.parser.Parser.compile(Parser.java:85)
	at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:132)
	at ch.qos.logback.classic.encoder.PatternLayoutEncoder.start(PatternLayoutEncoder.java:28)
	at org.springframework.boot.logging.logback.LogbackConfigurator.start(LogbackConfigurator.java:109)
	at org.springframework.boot.logging.logback.DefaultLogbackConfiguration.createAppender(DefaultLogbackConfiguration.java:154)
	at org.springframework.boot.logging.logback.DefaultLogbackConfiguration.consoleAppender(DefaultLogbackConfiguration.java:136)
	at org.springframework.boot.logging.logback.DefaultLogbackConfiguration.apply(DefaultLogbackConfiguration.java:86)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.lambda$loadDefaults$1(LogbackLoggingSystem.java:244)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.withLoggingSuppressed(LogbackLoggingSystem.java:483)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadDefaults(LogbackLoggingSystem.java:231)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:84)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:61)
...
```

As this worked fine with 1.5.12 and the logback upgrade is the only change I decided to report it first.

-----

be0b5e027487c351a0f006c2b695a7a3fcd4918d

**Comment by ceki** [comment]
This is a very useful report nonetheless. Thank you.
